name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-format:
    name: Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Call Dagger Function to build and test
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: latest
          # build-and-test is a function in the .dagger/dagger.gen.go file
          call: build-and-test --source .
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
